// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Weather.Data;

#nullable disable

namespace Weather.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Weather.Model.PermissibleLimits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxCO2")
                        .HasColumnType("float");

                    b.Property<double>("MaxHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MaxPM1")
                        .HasColumnType("float");

                    b.Property<double>("MaxPM10")
                        .HasColumnType("float");

                    b.Property<double>("MaxPM2_5")
                        .HasColumnType("float");

                    b.Property<double>("MaxTVOC")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PermissibleLimits");
                });

            modelBuilder.Entity("Weather.Model.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPermissibleLimitsId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserPermissibleLimitsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Weather.Model.User", b =>
                {
                    b.HasOne("Weather.Model.PermissibleLimits", "UserPermissibleLimits")
                        .WithMany()
                        .HasForeignKey("UserPermissibleLimitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPermissibleLimits");
                });
#pragma warning restore 612, 618
        }
    }
}
